In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/sylee/Documents/GitHub/DataSafe/DataSafe/행정동코드.csv")#, encoding = 'cp949')
df.head()

        법정동코드           법정동명
0  1111000000      서울특별시 종로구
1  1111010100  서울특별시 종로구 청운동
2  1111010200  서울특별시 종로구 신교동
3  1111010300  서울특별시 종로구 궁정동
4  1111010400  서울특별시 종로구 효자동

In [20]:
split = df.법정동명.str.split(' ')
split

0           [서울특별시, 종로구]
1      [서울특별시, 종로구, 청운동]
2      [서울특별시, 종로구, 신교동]
3      [서울특별시, 종로구, 궁정동]
4      [서울특별시, 종로구, 효자동]
             ...
487    [서울특별시, 강동구, 둔촌동]
488    [서울특별시, 강동구, 암사동]
489    [서울특별시, 강동구, 성내동]
490    [서울특별시, 강동구, 천호동]
491    [서울특별시, 강동구, 강일동]
Name: 법정동명, Length: 492, dtype: object

In [21]:
v_1 = split.str.get(0)
v_2 = split.str.get(1)
v_3 = split.str.get(2)
df['행정구역'], df['시군구'], df['읍면동'] = (v_1, v_2, v_3)
df.head()

        법정동코드           법정동명   행정구역  시군구  읍면동
0  1111000000      서울특별시 종로구  서울특별시  종로구  NaN
1  1111010100  서울특별시 종로구 청운동  서울특별시  종로구  청운동
2  1111010200  서울특별시 종로구 신교동  서울특별시  종로구  신교동
3  1111010300  서울특별시 종로구 궁정동  서울특별시  종로구  궁정동
4  1111010400  서울특별시 종로구 효자동  서울특별시  종로구  효자동

In [22]:
df.drop(columns = ['법정동명'], axis=1, inplace=True)

In [23]:
df

          법정동코드   행정구역  시군구  읍면동
0    1111000000  서울특별시  종로구  NaN
1    1111010100  서울특별시  종로구  청운동
2    1111010200  서울특별시  종로구  신교동
3    1111010300  서울특별시  종로구  궁정동
4    1111010400  서울특별시  종로구  효자동
..          ...    ...  ...  ...
487  1174010600  서울특별시  강동구  둔촌동
488  1174010700  서울특별시  강동구  암사동
489  1174010800  서울특별시  강동구  성내동
490  1174010900  서울특별시  강동구  천호동
491  1174011000  서울특별시  강동구  강일동

[492 rows x 4 columns]

In [24]:
%cd C:/Users/sylee/Documents/GitHub/DataSafe/DataSafe
df.to_csv('seoulareacode.csv', index=False)

C:\Users\sylee\Documents\GitHub\DataSafe\DataSafe

In [25]:
df_check = pd.read_csv("C:/Users/sylee/Documents/GitHub/DataSafe/DataSafe/seoulareacode.csv")
df_check

          법정동코드   행정구역  시군구  읍면동
0    1111000000  서울특별시  종로구  NaN
1    1111010100  서울특별시  종로구  청운동
2    1111010200  서울특별시  종로구  신교동
3    1111010300  서울특별시  종로구  궁정동
4    1111010400  서울특별시  종로구  효자동
..          ...    ...  ...  ...
487  1174010600  서울특별시  강동구  둔촌동
488  1174010700  서울특별시  강동구  암사동
489  1174010800  서울특별시  강동구  성내동
490  1174010900  서울특별시  강동구  천호동
491  1174011000  서울특별시  강동구  강일동

[492 rows x 4 columns]